### ISSUE TITLE
Find a way to make loldht calls quicker

### ISSUE THREAD

**Issue by brethash** [brethash/raspberium#1]
Currently awful response times. Pls fix ASAP ktx.

<img width="401" alt="screen shot 2016-08-29 at 9 01 17 pm" src="https://cloud.githubusercontent.com/assets/857165/18074755/3527ea2c-6e2c-11e6-8c64-bac7d5897434.png">

**Comment by brethash** [comment]
Its faster now after reducing the wait times in my forked [loldht library](https://github.com/brethash/lol_dht22)... I think the remaining time is due to network latency? Is there a better way!?

Yes. Probably via some sort of caching method.

**Comment by id-hash** [comment]
Turns out the DHT22 is sort of garbage/unreliable and is in the process of being deprecated. So this is no longer in scope.

**Comment by brethash** [comment]
Turns out the DHT22 is sort of garbage/unreliable and is in the process of being deprecated. So this is no longer in scope.
