### ISSUE TITLE
Add support for BME280 sensor

### ISSUE THREAD

**Issue by brethash** [brethash/raspberium#11]
Its quicker, better, faster than the DHT22. And provides pressure readings as well. Just do it.

**Comment by brethash** [comment]
https://github.com/BoschSensortec/BME280_driver/blob/master/bme280_support.c

**Comment by id-hash** [comment]
This will be initally addressed in the feature/bme280 branch. This change will also deprecate and remove DHT22 support. My experience has shown that the DHT22 is generally unreliable and not worth supporting especially now that there are smaller I2C only BME280 packages available like the one below.

https://smile.amazon.com/gp/product/B01LETIESU/ref=crt_ewc_title_gw_1?ie=UTF8&psc=1&smid=A3F3CVCOVVNP2J

**Comment by brethash** [comment]
This will be initally addressed in the feature/bme280 branch. This change will also deprecate and remove DHT22 support. My experience has shown that the DHT22 is generally unreliable and not worth supporting especially now that there are smaller I2C only BME280 packages available like the one below.

https://smile.amazon.com/gp/product/B01LETIESU/ref=crt_ewc_title_gw_1?ie=UTF8&psc=1&smid=A3F3CVCOVVNP2J

**Comment by brethash** [comment]
This will be initally addressed in the feature/bme280 branch. This change will also deprecate and remove DHT22 support. My experience has shown that the DHT22 is generally unreliable and not worth supporting especially now that there are smaller I2C only BME280 packages available like the one below.

https://smile.amazon.com/gp/product/B01LETIESU/ref=crt_ewc_title_gw_1?ie=UTF8&psc=1&smid=A3F3CVCOVVNP2J

**Comment by brethash** [comment]
Supported as of PR #22
