### ISSUE TITLE
Fix Google Charts js 

### ISSUE THREAD

**Issue by brethash** [brethash/raspberium#27]
Google changed stuff and several things about the implementation of their charts api. So none of the gauges on the front end work. Pls fix asap. Thx.

**Comment by id-hash** [comment]
> A Parser-blocking, cross-origin script, https://www.google.com/uds/?file=visualization&v=1&packages=gauge, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.

**Comment by id-hash** [comment]
This really only works in Firefox now, you schmo.

**Comment by brethash** [comment]
>A Parser-blocking, cross-origin script, https://www.google.com/uds/?file=visualization&v=1&packages=gauge, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.

**Comment by brethash** [comment]
This really only works in Firefox now, you schmo.

**Comment by develpr** [comment]
Nice!

**Comment by brethash** [comment]
This somehow isn't a "problem" now? I don't know what happened but I don't see the issue anymore. Closing for now. Will reopen if I see the issue crop up again.
