### ISSUE TITLE
Configuration examples

### ISSUE THREAD

**Issue by Kevinm94** [brethash/raspberium#34]
Do you have any configuration examples for setting up new installation? Does it have a web interface? 

Thanks

**Comment by brethash** [comment]
# Hey @kevinm94 !!!!!!!!

I apologize for not fully fleshing out my wiki on the configurations! It's been in the back of my brain to do for a while, but we recently moved and I haven't unpacked my Raspberium "dev kit" yet! You know what they same about [excuses](https://www.goodreads.com/quotes/tag/excuses) though... 

## Do you have any configuration examples for setting up new installation?
Kind of! From some of my notes I can tell you that the default I2C address for the BME280 package used in this project is 0x76. If you need to specify a different address, you can specify it in the database in the `devices` table. Not ideal I know...  I need to update the front end config options to support it for the actual interface. Beyond that particular value though, everything else is configurable in the web interface! See [https://github.com/brethash/raspberium/blob/master/database/seeds/ConfigurationsTableSeeder.php](https://github.com/brethash/raspberium/blob/master/database/seeds/ConfigurationsTableSeeder.php) for the default configuration values. 

## Does it have a web interface?
You betcha! It is a pretty responsive web interface. Admittedly, I'm not _the best_ front end developer on the planet, so I know there are plenty of improvements that could be made. But it is reasonably easy on the eyes and doesn't make me cry when I use it, so overall I'd chalk it up as a success in my book. It is also behind authentication (in case you want to make it available to potential prying eyes!!!) and the default credentials are `u: admin` `p: secret`. I would obviously highly recommend changing this password if you are going to make this accessible outside your network. I've been meaning to post screenshots to the [Raspberium Wiki](https://github.com/brethash/raspberium/wiki) for ages but it just sort of fell down the priority list. Whoops! From the web interface you can monitor the near-real time feed of the temperature and humidity, update your configuration values, and manually trigger your lights and misting system on/off.

## Thanks
You're very welcome. Please let me know what issues you come across. I know there are a few bugs floating around out there, but it was a fun project to play around with this past winter. I hope to get back to wrapping up some of the outstanding bugs in the next couple weeks. Thanks for checking the Raspberium out. :)

**Comment by Kevinm94** [comment]
Thanks for the reply. I have an extra RPi that I will give it try on. Do you know if it will support dht11 sensors? I have several left over from another project.

Thanks again !

**Comment by brethash** [comment]
So thats an interesting question! I actually originally designed everything to work with a DHT22 sensor! I tried a few of them and found them to be a bit unreliable, so I ended up moving to the BME280. By the grace of git, if you were a bit code savvy, you could pretty easily harvest my deprecated DHT22 code and plug it in (maybe in a forked repo or your own local branch?). 

The last commit that was merged to master before I deprecated the DHT22 code was [https://github.com/brethash/raspberium/commit/d3d2bedf21170efc0fc3e9d75c4bd64f6a7d1f88](https://github.com/brethash/raspberium/commit/d3d2bedf21170efc0fc3e9d75c4bd64f6a7d1f88). 

Let me know how it works out for you!
